package events

type BallHitData struct {
	Players []struct{ // Players that hit the ball that frame.
		Name string `json:"Name"` // Display name.
		Shortcut int64 `json:"Shortcut"` // Spectator shortcut.
		TeamNum int64 `json:"TeamNum"` // Team index (0 = Blue, 1 = Orange).
	} `json:"Players"`
	Ball struct{ // Ball state at the moment of the hit.
		PreHitSpeed float64 `json:"PreHitSpeed"` // Ball speed before the hit (Unreal Units/second).
		PostHitSpeed float64 `json:"PostHitSpeed"` // Ball speed after the hit (Unreal Units/second).
		Location struct {X float64; Y float64; Z float64} `json:"Location"` // World position (X, Y, Z) of the ball at impact.
	} `json:"Ball"`
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js