package events

type ClockUpdatedSecondsData struct {
	TimeSeconds int64 `json:"TimeSeconds"` // Seconds remaining in the match.
	BOvertime bool `json:"bOvertime"` // True if the game is in overtime.
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js