package events

type CrossbarHitData struct {
	BallSpeed float64 `json:"BallSpeed"` // Ball speed on impact.
	ImpactForce float64 `json:"ImpactForce"` // Impact force of the ball relative to the crossbar normal.
	BallLastTouch struct{ // The last touch of the ball before the crossbar hit.
		Player struct{ // The player who made the last touch.
			Name string `json:"Name"` // Display name.
			Shortcut int64 `json:"Shortcut"` // Spectator shortcut.
			TeamNum int64 `json:"TeamNum"` // Team index (0 = Blue, 1 = Orange).
		} `json:"Player"`
		Speed float64 `json:"Speed"` // Speed of the ball resulting from this hit.
	} `json:"BallLastTouch"`
	BallLocation struct {X float64; Y float64; Z float64} `json:"BallLocation"` // World position (X, Y, Z) of the ball when the impact occurred.
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js