package events

type GoalScoredData struct {
	GoalSpeed float64 `json:"GoalSpeed"` // Speed of the ball (Unreal Units/second) when it crossed the goal line.
	GoalTime float64 `json:"GoalTime"` // Length of the previous round in seconds.
	ImpactLocation struct {X float64; Y float64; Z float64} `json:"ImpactLocation"` // World position (X, Y, Z) of the ball when the goal was scored.
	Scorer struct{ // The player who scored the goal.
		Name string `json:"Name"` // Display name of the scorer.
		Shortcut int64 `json:"Shortcut"` // Spectator shortcut.
		TeamNum int64 `json:"TeamNum"` // Team index of the scorer.
	} `json:"Scorer"`
	BallLastTouch struct{ // The last touch of the ball before the goal.
		Player struct{ // The player who made the last touch.
			Name string `json:"Name"` // Name of the player who last touched the ball.
			Shortcut int64 `json:"Shortcut"` // Spectator shortcut.
			TeamNum int64 `json:"TeamNum"` // Team index.
		} `json:"Player"`
		Speed float64 `json:"Speed"` // Speed of the ball resulting from this touch.
	} `json:"BallLastTouch"`
	Assister struct{ // CONDITIONALSame shape as Scorer. Present only when an assist was recorded.
	} `json:"Assister"`
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js