package events

type MatchEndedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
	WinnerTeamNum int64 `json:"WinnerTeamNum"` // Team index of the winning team.
}
// Generated by scripts/structsToGo.js