package events

type StatfeedEventData struct {
	EventName string `json:"EventName"` // Asset name of the StatEvent (e.g. "Demolish", "Save").
	Type string `json:"Type"` // Localized display label for the stat (e.g. "Demolition").
	MainTarget struct{ // Player who earned the stat.
		Name string `json:"Name"` // Display name.
		Shortcut int64 `json:"Shortcut"` // Spectator shortcut.
		TeamNum int64 `json:"TeamNum"` // Team index (0 = Blue, 1 = Orange).
	} `json:"MainTarget"`
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
	SecondaryTarget struct{ // CONDITIONALPlayer involved in the stat (e.g. the demolished player). Same shape as MainTarget.
	} `json:"SecondaryTarget"`
}
// Generated by scripts/structsToGo.js