package events

type UpdateStateData struct {
	Players []struct{ // One entry per player in the match.
		Name string `json:"Name"` // Display name.
		PrimaryId string `json:"PrimaryId"` // Platform identifier in the format Platform|Uid|Splitscreen (e.g. "Steam|123|0", "Epic|456|0").
		Shortcut int64 `json:"Shortcut"` // Spectator shortcut number.
		TeamNum int64 `json:"TeamNum"` // Team index (0 = Blue, 1 = Orange).
		Score int64 `json:"Score"` // Total match score.
		Goals int64 `json:"Goals"` // Goals scored this match.
		Shots int64 `json:"Shots"` // Shot attempts this match.
		Assists int64 `json:"Assists"` // Assists earned this match.
		Saves int64 `json:"Saves"` // Saves made this match.
		Touches int64 `json:"Touches"` // Total ball touches.
		CarTouches int64 `json:"CarTouches"` // Touches by the car body (not ball).
		Demos int64 `json:"Demos"` // Demolitions inflicted.
		BHasCar bool `json:"bHasCar"` // SPECTATORTrue if the player currently has a vehicle.
		Speed float64 `json:"Speed"` // SPECTATORVehicle speed in Unreal Units/second.
		Boost int64 `json:"Boost"` // SPECTATORBoost amount 0–100.
		BBoosting bool `json:"bBoosting"` // SPECTATORTrue if the player is currently boosting.
		BOnGround bool `json:"bOnGround"` // SPECTATORTrue if at least 3 wheels are touching the world.
		BOnWall bool `json:"bOnWall"` // SPECTATORTrue if the vehicle is on a wall.
		BPowersliding bool `json:"bPowersliding"` // SPECTATORTrue if the player is holding handbrake.
		BDemolished bool `json:"bDemolished"` // SPECTATORTrue if the vehicle is currently destroyed.
		BSupersonic bool `json:"bSupersonic"` // SPECTATORTrue if the vehicle is at supersonic speed.
		Attacker struct{ // CONDITIONALThe player who demolished this player. Present only when demolished.
			Name string `json:"Name"` // Name of the player who demolished this player.
			Shortcut int64 `json:"Shortcut"` // Spectator shortcut of the attacker.
			TeamNum int64 `json:"TeamNum"` // Team index of the attacker.
		} `json:"Attacker"`
	} `json:"Players"`
	Game struct{ // Match metadata.
		Teams []struct{ // One entry per team, ordered by TeamNum.
			Name string `json:"Name"` // Team name.
			TeamNum int64 `json:"TeamNum"` // Team index.
			Score int64 `json:"Score"` // Team goal count.
			ColorPrimary string `json:"ColorPrimary"` // Hex color code (no #) for the team’s primary color.
			ColorSecondary string `json:"ColorSecondary"` // Hex color code for the team’s secondary color.
		} `json:"Teams"`
		TimeSeconds int64 `json:"TimeSeconds"` // Seconds remaining in the match.
		BOvertime bool `json:"bOvertime"` // True if the match is in overtime.
		Ball struct{ // Current ball state.
			Speed float64 `json:"Speed"` // Current ball speed in Unreal Units/second.
			TeamNum int64 `json:"TeamNum"` // Index of the last team to touch the ball. 255 if the ball has not been touched.
		} `json:"Ball"`
		BReplay bool `json:"bReplay"` // True if a goal replay or history replay is active.
		BHasWinner bool `json:"bHasWinner"` // True if a team has won.
		Winner string `json:"Winner"` // Name of the winning team. Empty string if no winner yet.
		Arena string `json:"Arena"` // Asset name of the current map (e.g. "Stadium_P").
		BHasTarget bool `json:"bHasTarget"` // True if the client is currently viewing a specific vehicle.
		Target struct{ // CONDITIONALPlayer currently being viewed. Members are an empty string or 0 if the player does not have a spectator target.
			Name string `json:"Name"` // Name of the player being viewed.
			Shortcut int64 `json:"Shortcut"` // Spectator shortcut of the viewed player.
			TeamNum int64 `json:"TeamNum"` // Team index of the viewed player.
		} `json:"Target"`
		Frame int64 `json:"Frame"` // CONDITIONALCurrent frame number if a replay is active.
		Elapsed float64 `json:"Elapsed"` // CONDITIONALSeconds elapsed since game start if a replay is active.
	} `json:"Game"`
}
// Generated by scripts/structsToGo.js