import { join } from "path";
import { writeFile, readFile, appendFile } from "fs/promises";

const JSON_DEST = join(import.meta.dirname, '..', 'data');
const EVENT_NAMES_NAME = "eventnames.json"
const EVENT_DESCRIPTIONS_NAME = "eventdescriptions.json"
const EVENT_STRUCTS_NAME = "eventstructures.json"
const EVENTS_DEST = join(import.meta.dirname, '..', 'events');
const LISTENER_DEST = join(import.meta.dirname, '..', 'internal', 'listener', 'listener.go');
const PARSER_DEST = join(import.meta.dirname, '..', 'parser.go');
const PARSER_TEST_DEST = join(import.meta.dirname, '..', 'parser_test.go');

const EVENT_FWDS = {

}

const LISTENER_SWITCH_TAG = 'LISTEN EVENT SWITCH';
const SUBSCRIBER_EXPORT_TAG = 'SUBSCRIBER EXPORT';
const EVENTS_TEST_TAG = 'TEST EVENTS';
const EVENT_PUBLISHERS_TAG = 'EVENT PUBLISHER STRUCT';
const EVENT_PUBLISHERS_INIT_TAG = 'INIT PUBLISHER STRUCT';
const PARSER_SUBSCRIBERS_TAG = 'PARSER SUBSCRIBERS';
const INIT_PARSER_SUBSCRIBERS_TAG = 'INIT PARSER SUBSCRIBERS';
const EVENT_TYPE_EXPORTS_TAG = 'EVENT TYPE EXPORTS';

const EVENT_STRUCT_PREAMBLE = `package events\n\n`;

const STATIC_TYPE_TRANSLATIONS = {
    string: "string",
    bool: "bool",
    int: "int64",
    float: "float64",
    vector: "struct {X float64; Y float64; Z float64}"
}

const DYNAMIC_TYPE_TRANSLATIONS = {
    object: "struct{",
    array: "[]struct{"
}

function startTag(tag) {
    return `// START ${tag}`
}

function endTag(tag) {
    return `// END ${tag}`
}

async function readJSON(filename) {
    const text = await readFile(filename, "utf8");
    return JSON.parse(text);
}

async function appendWithTabs(dest, content, tabCount) {
    const tabs = "\t".repeat(tabCount);
    return await appendFile(dest, `${tabs}${content}`);
}

async function writeField(filename, fieldName, fieldStruct, tabs) {
    const publicFieldName = fieldName[0].toUpperCase() + fieldName.slice(1);
    await appendWithTabs(filename, `${publicFieldName} ${STATIC_TYPE_TRANSLATIONS[fieldStruct.fieldType] || DYNAMIC_TYPE_TRANSLATIONS[fieldStruct.fieldType]}${STATIC_TYPE_TRANSLATIONS[fieldStruct.fieldType] ? ` \`json:"${fieldName}"\`` : ''} // ${fieldStruct.description}\n`, tabs)

    // If dynamic type, need to recursive write nested fields
    if (DYNAMIC_TYPE_TRANSLATIONS[fieldStruct.fieldType]) {
        // Recursive call to write nested fields
        for (const [nestedFieldName, nestedFieldStruct] of Object.entries(fieldStruct.subFields)) {
            await writeField(filename, nestedFieldName, nestedFieldStruct, tabs + 1);
        }
        await appendWithTabs(filename, `} \`json:"${fieldName}"\`\n`, tabs);
    }
}

async function writeStructToFile(eventName, struct, description) {
    // Reset file if it exists, give it the preamble
    const dest = join(EVENTS_DEST, `${eventName}.go`);
    await writeFile(dest, EVENT_STRUCT_PREAMBLE);

    await appendFile(dest, `// ${description}\ntype ${eventName}Data struct {\n`)

    const tabs = 1; // Start at 1 tab for written fields
    for (const [fieldName, fieldStruct] of Object.entries(struct)) {
        await writeField(dest, fieldName, fieldStruct, tabs);
    }
    await appendFile(dest, '}\n');

    await appendFile(dest, '// Generated by scripts/structsToGo.js');
}

async function writeToTags(dest, tag, contents) {
    let fileContents = await readFile(dest, 'utf8');
    const startIdx = fileContents.indexOf(startTag(tag));
    const endIdx = fileContents.indexOf(endTag(tag));

    if (startIdx === -1 || endIdx === -1) {
        console.error(`Could not find ${tag} in ${dest}!`);
        return;
    }

    let newContents = fileContents.substring(0, startIdx + startTag(tag).length) + "\n" + contents + fileContents.substring(endIdx);
    return await writeFile(dest, newContents);
}

async function writeListenerSwitch(eventNames) {
    let newContents = "";
    for (const eventName of eventNames) {
        newContents += `\tcase "${eventName}":\n`;
        newContents += `\t\tvar parsed events.${eventName}Data\n`;
        newContents += `\t\tif err := json.Unmarshal(data, &parsed); err != nil {\n`;
        newContents += `\t\t\tfmt.Printf("Failed to unmarshal ${eventName} data: %v.", err)\n`;
        newContents += `\t\t\treturn\n`;
        newContents += `\t\t}\n`;
        newContents += `\t\tpublishers.${eventName}.Publish(parsed)\n`;
    }
    // Write fwd cases
    for (const [from, to] of Object.entries(EVENT_FWDS)) {
        newContents += `\tcase "${from}":\n`;
        newContents += `\t\tvar parsed events.${to}Data\n`;
        newContents += `\t\tif err := json.Unmarshal(data, &parsed); err != nil {\n`;
        newContents += `\t\t\tfmt.Printf("Failed to unmarshal ${from} data: %v.", err)\n`;
        newContents += `\t\t\treturn\n`;
        newContents += `\t\t}\n`;
        newContents += `\t\tpublishers.${to}.Publish(parsed)\n`;
    }
    return await writeToTags(LISTENER_DEST, LISTENER_SWITCH_TAG, newContents);
}

async function writeEventTests(eventNames) {
    let contents = "";
    for (const eventName of eventNames) {
        contents += `var test${eventName} = flag.Bool("${eventName.toLowerCase()}", false, "test event ${eventName}")\nfunc Test${eventName}(t* testing.T) {\n\tif !*test${eventName} && !*testAll {\n\t\tt.Skip("skipping test of ${eventName}")\n\t}\n\tch := parser.${eventName}.Subscribe()\n\tselect {\n\tcase <-ch:\n\t\tbreak\n\tcase <-time.After(time.Duration(*testTimeoutSeconds) * time.Second):\n\t\tt.Errorf("Failed to receive ${eventName} event")\n\t}\n}\n\n`
    }

    return await writeToTags(PARSER_TEST_DEST, EVENTS_TEST_TAG, contents);
}

async function writeEventPublishers(eventNames) {
    let contentsType = "";
    let contentsInit = "";
    for (const eventName of eventNames) {
        contentsType += `\t${eventName} publisher.Publisher[events.${eventName}Data]\n`;
        contentsInit += `\t\t${eventName}: publisher.New[events.${eventName}Data]("${eventName}"),\n`
    }

    await writeToTags(LISTENER_DEST, EVENT_PUBLISHERS_TAG, contentsType);
    await writeToTags(LISTENER_DEST, EVENT_PUBLISHERS_INIT_TAG, contentsInit);
}

async function writeParserSubscribers(eventNames) {
    let contentsType = "\n";
    let contentsInit = "";
    for (const eventName of eventNames) {
        contentsType += `\t${eventName} Subscriber[events.${eventName}Data]\n`;
        contentsInit += `\t\t ${eventName}: newSubscriber(publishers.${eventName}),\n`
    }

    await writeToTags(PARSER_DEST, PARSER_SUBSCRIBERS_TAG, contentsType);
    await writeToTags(PARSER_DEST, INIT_PARSER_SUBSCRIBERS_TAG, contentsInit);
}

async function main() {
    const write = async (dest, label, callback, ...args) => {
        console.log(`Writing ${label} to ${dest}`);
        await callback(...args);
        console.log(`Finished writing ${label}\n${'-'.repeat(50)}`);
    }
    try {
        const eventNames = await readJSON(join(JSON_DEST, EVENT_NAMES_NAME));
        const eventDescriptions = await readJSON(join(JSON_DEST, EVENT_DESCRIPTIONS_NAME));
        const eventStructs = await readJSON(join(JSON_DEST, EVENT_STRUCTS_NAME));

        for (const [name, struct] of Object.entries(eventStructs)) {
            await write(`${EVENTS_DEST}/${name}.go`, `struct for event ${name}`, writeStructToFile, name, struct, eventDescriptions[eventNames.indexOf(name)]);
        }

        await write(LISTENER_DEST, 'listener switch', writeListenerSwitch, eventNames);
        await write(LISTENER_DEST, 'event publishers type and initialization', writeEventPublishers, eventNames);
        await write(PARSER_DEST, 'parser subscribers type and initialization', writeParserSubscribers, eventNames);
        await write(PARSER_DEST, 'event tests', writeEventTests, eventNames);

    } catch (e) {
        console.error("Error:", e);
    }
}

main();